version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    working_dir: /workspace/apps/frontend
    ports:
      - "4321:4321"
    environment:
      NODE_ENV: production
      BASE_FQDN: "http://flightcore.raqz.link" # Replace with your app's base FQDN
      PUBLIC_BOOKING_IFRAME_SRC: "https://flightcore.pl/booking"
      CONTACT_WEBHOOK_URL: "https://n8ndev.flightcore.pl/webhook/de6f4b9c-8eef-4729-9d24-ed01fc42ee19"
      CONTACT_WEBHOOK_TOKEN_KEY: "VY8uNG6M2ey6P2DthYkD"
      CONTACT_WEBHOOK_TOKEN_VALUE: "kJF59YQ7mV7vJ3ueEjPE"
    volumes:
      - .:/workspace
