name: 'Deploy Astro to VPS (SFTP)'
description: 'Builds and deploys an Astro site to a VPS using SFTP.'
inputs:
  server:
    description: 'SFTP server address'
    required: true
  username:
    description: 'SFTP username'
    required: true
  password:
    description: 'SFTP password'
    required: true
  server-dir:
    description: 'Remote directory to deploy to'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Code Setup
      uses: ./code-setup/action.yml 

    - name: Build Astro site
      uses: astro-build/action@v1

    - name: Deploy to VPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ inputs.server }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        local-dir: "apps/frontend/dist/"
        server-dir: ${{ inputs.server-dir }}
