name: Code Quality
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  code_quality:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Code Setup
        uses: ./.github/actions/code-setup

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm frontend build
